apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-vol
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/postgres_data"
