apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-file
  labels:
    type: local
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/static_html"
