apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yaml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 3
  selector:
     matchLabels:
       io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - gunicorn
        - --bind
        - 0.0.0.0:5000
        - manage:app
        env:
        - name: APP_FOLDER
          valueFrom:
            configMapKeyRef:
              key: APP_FOLDER
              name: web-env-prod
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              key: DATABASE
              name: web-env-prod
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: web-env-prod
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              key: FLASK_APP
              name: web-env-prod
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              key: FLASK_ENV
              name: web-env-prod
        - name: SQL_HOST
          valueFrom:
            configMapKeyRef:
              key: SQL_HOST
              name: web-env-prod
        - name: SQL_PORT
          valueFrom:
            configMapKeyRef:
              key: SQL_PORT
              name: web-env-prod
        image: flask-on-docker_web 
        name: web
        resources: {}
        volumeMounts:
        - mountPath: /home/app/web/project/static
          name: static-volume
      restartPolicy: Always
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume
status: {}
